print("February 5, 2023")
print("Feeling like I won't be able to leave my current job after so many rejections")
print("I have to master python and try to get more comfortable programming")
print("")
print("ʕノ•ᴥ•ʔノ ︵ ┻━┻")

print('+---------------------------------------------------------------------+')
print('|                                                       February 2023 |')
print('|                                                         Anaheim, CA |')
print('|  Dear Self,                                                         |')
print('|                                                                     |')
print('|      Master python and get the job that you always wanted.          |')
print('|      Don\'t give up and keep going                                  |')
print('|      So there is a difference from today                            |')
print('|      Rejection is a part of life                                    |')
print('|      And always get back up.                                        |')
print('|                                                                     |')
print('|                                    Bryan Aguiar  ʕノ•ᴥ•ʔノ ︵ ┻━┻    |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')